### ISSUE TITLE
We need collaborators

### ISSUE THREAD

**Issue by tradzik** [anti-poxip/anti-poxip-official-virus#1]
guyz... if we dont start working on this vir, we wont ever finish it!

**Comment by i5o** [comment]
I can help here.

**Comment by ty221** [comment]
gr8 watz ur favurite programm-lang?

**Comment by i5o** [comment]
i laik ada

Ignacio Rodríguez
SugarLabs at Facebook
<https://www.facebook.com/pages/SugarLabs/187845102582>

2015-03-25 10:43 GMT-03:00 Tymon Radzik <notifications@github.com>:

**Comment by ty221** [comment]
gr8 wi can start workyng

**Comment by ninjagolloyd** [comment]
Can I help?

**Comment by ty221** [comment]
Yes

pon., 1.06.2015 o 15:32 użytkownik ninjagolloyd <notifications@github.com>
napisał:

**Comment by ninjagolloyd** [comment]
What did you just say???????????!!!!!!!!!

**Comment by ty221** [comment]
You can help us!!!

pon., 1.06.2015 o 15:45 użytkownik ninjagolloyd <notifications@github.com>
napisał:

**Comment by ninjagolloyd** [comment]
K. I got confused by the email thingamajig.

**Comment by i5o** [comment]
You can help yas

**Comment by ninjagolloyd** [comment]
K

**Comment by i5o** [comment]
But, why?

Ignacio Rodríguez
SugarLabs at Facebook
<https://www.facebook.com/pages/SugarLabs/187845102582>

2016-02-15 17:02 GMT-03:00 Tymon Radzik <notifications@github.com>:

**Comment by tradzik** [comment]
Cus no1 wantz to wrk with as
On Mon, 15 Feb 2016 at 21:46, Ignacio Rodríguez <notifications@github.com>
wrote:

> But, why?
>
> Ignacio Rodríguez
> SugarLabs at Facebook
> <https://www.facebook.com/pages/SugarLabs/187845102582>
>
> 2016-02-15 17:02 GMT-03:00 Tymon Radzik <notifications@github.com>:
>
> > Closed #1
> > <https://github.com/anti-poxip/anti-poxip-official-virus/issues/1>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/anti-poxip/anti-poxip-official-virus/issues/1#event-551152382
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/anti-poxip/anti-poxip-official-virus/issues/1#issuecomment-184387084>
> .
>
-- 
Z poważaniem,
Tymon Radzik

**Comment by i5o** [comment]
ok, reply to me in telegram, bye

Ignacio Rodríguez
SugarLabs at Facebook
<https://www.facebook.com/pages/SugarLabs/187845102582>

2016-02-15 18:03 GMT-03:00 Tymon Radzik <notifications@github.com>:
